[feat][plugins/aws] Support for Aws SageMaker
someengineering/resoto pull request #1372
Opened 2023-01-16 17:11 UTC by anjafr

# Description

# To-Dos

- [ ] Add test coverage for new or updated functionality
- [ ] Lint and test with `tox`
- [ ] Document new or updated functionality (someengineering/resoto.com#XXXX)

# Issues Fixed

- Fixes #XXXX

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

2023-01-17 10:02 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/resource/sagemaker.py
> +    scaling_type: Optional[str] = field(default=None)
same definition - can be one kind.

2023-01-17 10:24 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/resource/sagemaker.py
> +class AwsSagemakerAutoMLJob(AwsResource):
Would it make sense to define an abstract `AwsSagemakerJob` class? 
A couple of attributes are shared between all jobs.

2023-01-17 10:28 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/resource/sagemaker.py
> +    categorical_parameter_ranges: List[AwsSagemakerCategoricalParameter] = field(factory=list)
That's basically a simple list - consider to remove this type

2023-01-17 10:29 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/resource/sagemaker.py
> +    content_classifiers: List[str] = field(factory=list)
This is a simple list - consider to remove it.

2023-01-17 12:45 UTC, anjafr commented
> I saw a couple of properties that are reference ids to other resources. We can drop the id if the edge is semantically the same as having the id (e.g. this is not true if you have multiple relationships for different properties). I only marked some examples - please walk the list of resources if there are more.

@aquamatthias I'm not sure I understand. Do you mean that we should add the edges from the `source` information directly? That's certainly possible, but it would be different to the way we do it for (afaik) every other service so far 🤔

2023-01-18 08:12 UTC, aquamatthias commented
> > I saw a couple of properties that are reference ids to other resources. We can drop the id if the edge is semantically the same as having the id (e.g. this is not true if you have multiple relationships for different properties). I only marked some examples - please walk the list of resources if there are more.
> 
> @aquamatthias I'm not sure I understand. Do you mean that we should add the edges from the `source` information directly? That's certainly possible, but it would be different to the way we do it for (afaik) every other service so far 🤔

Yes. See ec2 for examples.

2023-01-18 10:39 UTC, anjafr commented
> Yes. See ec2 for examples.

Yea I see 🤔 I'm a bit confused as to why this hasn't come up for past services/resources? I haven't added edges from source anywhere until now (always from the resource model properties) so it would be quite a break from that. And should this then be done retrospectively for all other resources as well? That's quite a big task, so I wonder..

2023-01-18 14:53 UTC, anjafr commented
> I also remember that you wanted to introduce an abstract class for all jobs?

So I've been looking at all the job models and it doesn't actually lend itself to an abstract `job` class. The similarities don't hold up. Most jobs have something like Input- and Output-Config for example, but what's inside those differs from job type to job type. Same with VPC-Config - most jobs have it somewhere, but at varying levels of nested information 🤷🏻‍♀️ 

What I originally wanted to have (and still do) is a way to search for instances of any job type at once. Something that would behave as if we had `kind=aws_sagemaker_job` in a search. But I'm not sure how to go about that without overriding the individual kinds of each job 🤔

2023-01-20 15:36 UTC, aquamatthias requested changes
Collected AWS sagemaker resources - worked!
I see this error in the logs:
```
ERROR|Duplicate checksum z3wG8LHnb4lcaQ3gT03u9Q for node aws_sagemaker_app default in graph
```

This indicates that the key properties for sagemaker apps are not unique.

I tried to cleanup resources and got those errors:

```
23-01-20 16:33:23|ERROR|An error occurred during clean up aws_sagemaker_app datascience-1-0-ml-t3-medium-ad10824985c0f8abb6eaad94debc in account someengineering (882347060974) region eu-central-1
Traceback (most recent call last):
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/__init__.py", line 343, in cleanup
    if deleted := resource.delete_resource(client):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/resource/sagemaker.py", line 819, in delete_resource
    client.call(
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/resotolib/resotolib/utils.py", line 154, in timer
    ret = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/aws_client.py", line 141, in call
    return self.call_single(aws_service, action, result_name, max_attempts=5, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/aws_client.py", line 119, in call_single
    result = getattr(client, py_action)(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/client.py", line 515, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/client.py", line 893, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/client.py", line 964, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "UserProfileName"
Unknown parameter in input: "SpaceName", must be one of: DomainId, UserProfileName, AppType, AppName
23-01-20 16:33:23|ERROR|An error occurred during clean up aws_sagemaker_app default in account someengineering (882347060974) region eu-central-1
Traceback (most recent call last):
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/__init__.py", line 343, in cleanup
    if deleted := resource.delete_resource(client):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/resource/sagemaker.py", line 819, in delete_resource
    client.call(
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                      ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/resotolib/resotolib/utils.py", line 154, in timer
    ret = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/aws_client.py", line 141, in call
    return self.call_single(aws_service, action, result_name, max_attempts=5, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/plugins/aws/resoto_plugin_aws/aws_client.py", line 119, in call_single
    result = getattr(client, py_action)(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/client.py", line 515, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/client.py", line 893, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/client.py", line 964, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthias/Documents/Work/someeng/resoto/venv/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "UserProfileName"
Unknown parameter in input: "SpaceName", must be one of: DomainId, UserProfileName, AppType, AppName
```

Can you take a look?

2023-01-23 09:52 UTC, anjafr commented
`Unknown parameter in input: "SpaceName", must be one of: DomainId, UserProfileName, AppType, AppName`
That's funny though. The docs say that you have to either put `UserProfileName` OR `SpaceName`. This error message seems to imply though that `SpaceName` is useless as a parameter for this command?
<img width="708" alt="image" src="https://user-images.githubusercontent.com/66877958/214009876-c96b8ae8-78c8-42bd-8ef9-b485c8382efe.png">

I've now made it so that the deletion command uses `UserProfileName`, if that value is set. And if not, the deletion command is tried with `SpaceName` instead. 🤷🏻‍♀️

2023-01-23 10:44 UTC, anjafr commented
> I see this error in the logs:
> 
> ```
> ERROR|Duplicate checksum z3wG8LHnb4lcaQ3gT03u9Q for node aws_sagemaker_app default in graph
> ```
> 
> This indicates that the key properties for sagemaker apps are not unique.

Hm hm hm. Don't fully underststand this one. What exactly does it mean? I just checked if there's any other resource anywhere that has properties of the same time, but there is none?

2023-01-24 16:25 UTC, aquamatthias approved these changes
One nit - otherwise lgtm. thanks!

2023-01-24 16:25 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/aws_client.py
> +            return None
why would we swallow client errors?
I would opt to remove the try/except block

2023-01-24 16:34 UTC, aquamatthias approved these changes
🚀 👍

2023-01-24 16:46 UTC, merged