[plugins/aws][fix] Use a real aws cli instead of translating to boto3 APIs
someengineering/resoto pull request #1687
Opened 2023-06-23 15:05 UTC by meln1k

# Description

# To-Dos

- [ ] Add test coverage for new or updated functionality
- [ ] Lint and test with `tox`
- [ ] Document new or updated functionality (someengineering/resoto.com#XXXX)

# Issues Fixed

- Fixes #XXXX

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

2023-06-23 15:33 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/__init__.py
> -        client = get_client(current_config(), resource) if resource else create_client()
Region is coming from the resource.

2023-06-23 15:58 UTC, aquamatthias requested changes
Resource-specific properties need to be fetched from the resource.

2023-06-26 14:02 UTC, aquamatthias commented on plugins/aws/resoto_plugin_aws/__init__.py
> +            ac = resource.account(self.graph)
Does `self.graph` makes sense? Irritating from my POV.

2023-06-26 14:09 UTC, meln1k commented on plugins/aws/resoto_plugin_aws/__init__.py
> +            ac = resource.account(self.graph)
good point, fixed

2023-06-26 16:02 UTC, aquamatthias submitted a review, later dismissed
thanks

2023-06-27 08:58 UTC, aquamatthias approved these changes
Thanks!

2023-06-27 08:59 UTC, merged